### PR TITLE
Fix timestretch

### LINKED ISSUE #13: Change BPM does not process entire file
When using the quantize option with a slower bpm, the result files seem to drop audio towards the end of the file.

Steps to reproduce (from empty DB):

1. `python polymath.py -a I32Dwc242Cs` (adds a 1-minute beat from YouTube for testing)
2. `python polymath.py -q all -t 50` (attempts to change bpm from ~105 to 50)

Expected result:
Output files in 'processed' should be ~2x the length of the original, because bpm is ~half the original.

Actual result:
Output files in 'processed' are exact same length as the source file. Beat quantization seems to die out near the end of the original file.

### PR DESCRIPTION
**Pull request by eljeff**
Fixes https://github.com/samim23/polymath/issues/13

- Calculate actual new length of the result files
- Don't worry if resulting time_map point falls outside of original file length
- Use new length for final time_map entry

### CODE REVIEW

**Comment by samim23** [comment]
This is fantastic! thank you so much for spotting this and fixing it, you rock!

**Comment by samim23** [comment]
Mmmh.. there seems to be a bug in your code. When i try to quantize something to a slower BPM than the original, i get the error `ValueError: time_map is not monotonic`. pyrubberband is very specific and i've hassled with it already for some time. Not entirely sure how to fix it. Any ideas? Rolling back this fix for now.

**Comment by samim23** [comment]
just for reference, i encounter the bug mentioned above with your changes, when trying to test on this video:
`python polymath.py -q 6QImCMjW-PM -t 120`

**Comment by eljeff** [comment]
> Mmmh.. there seems to be a bug in your code. When i try to quantize something to a slower BPM than the original, i get the error `ValueError: time_map is not monotonic`. pyrubberband is very specific and i've hassled with it already for some time. Not entirely sure how to fix it. Any ideas? Rolling back this fix for now.

Not really - this is the first python code I've ever committed. 
Pretty sure the mechanism to fix the processing is sound though.
I don't get that error on my configuration. If you can get a line number and the exact error I'll look around.

Thank you!

**Comment by samim23** [comment]
The line `strechedaudio = pyrb.timemap_stretch(y, sr, time_map)` throws the error `ValueError: time_map is not monotonic` with your code, when i try to quantize the video `6QImCMjW-PM` to 120BPM. The timemap it requests is really fiddly.

https://pyrubberband.readthedocs.io/en/stable/generated/pyrubberband.pyrb.timemap_stretch.html

**Comment by eljeff** [comment]
Thanks for confirming.
I was able to get the error, so I'm looking at it.

Good call on the track too

**Comment by eljeff** [comment]
I looked up the definition of monotonic, and after inspecting the data, it made total sense why it wouldn't work, so I've implemented a fix.
https://github.com/samim23/polymath/pull/16

Thanks again!

**Pull request merged**
